# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_sauvegarde.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageSauvegarde(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_sauvegarde = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.message_sauvegarde.setFont(font)
        self.message_sauvegarde.setAlignment(QtCore.Qt.AlignCenter)
        self.message_sauvegarde.setWordWrap(True)
        self.message_sauvegarde.setObjectName("message_sauvegarde")
        self.verticalLayout.addWidget(self.message_sauvegarde)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.combobox_sauvegarde = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_sauvegarde.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.combobox_sauvegarde.setFont(font)
        self.combobox_sauvegarde.setObjectName("combobox_sauvegarde")
        self.verticalLayout_2.addWidget(self.combobox_sauvegarde)
        self.bouton_selectionner_sauvegarde = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_selectionner_sauvegarde.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_selectionner_sauvegarde.setFont(font)
        self.bouton_selectionner_sauvegarde.setObjectName("bouton_selectionner_sauvegarde")
        self.verticalLayout_2.addWidget(self.bouton_selectionner_sauvegarde)
        self.bouton_supprimer_sauvegarde = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_supprimer_sauvegarde.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_supprimer_sauvegarde.setFont(font)
        self.bouton_supprimer_sauvegarde.setObjectName("bouton_supprimer_sauvegarde")
        self.verticalLayout_2.addWidget(self.bouton_supprimer_sauvegarde)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.message_sauvegarde.setText(_translate("MainWindow", "<html><head/><body><p>Selectionnez la sauvegarde que vous </p><p>voulez continuer ou supprimer</p></body></html>"))
        self.bouton_selectionner_sauvegarde.setText(_translate("MainWindow", "Selectionner"))
        self.bouton_supprimer_sauvegarde.setText(_translate("MainWindow", "Supprimer"))
