# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_creation_personnage_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageCreationPersonnage1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_creation_personnage_1 = QtWidgets.QLabel(self.centralwidget)
        self.message_creation_personnage_1.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.message_creation_personnage_1.setFont(font)
        self.message_creation_personnage_1.setAlignment(QtCore.Qt.AlignCenter)
        self.message_creation_personnage_1.setObjectName("message_creation_personnage_1")
        self.verticalLayout.addWidget(self.message_creation_personnage_1)
        self.bouton_generer_endurance = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_generer_endurance.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_generer_endurance.setFont(font)
        self.bouton_generer_endurance.setObjectName("bouton_generer_endurance")
        self.verticalLayout.addWidget(self.bouton_generer_endurance)
        self.label_endurance = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_endurance.setFont(font)
        self.label_endurance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_endurance.setObjectName("label_endurance")
        self.verticalLayout.addWidget(self.label_endurance)
        self.bouton_generer_habilete = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_generer_habilete.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_generer_habilete.setFont(font)
        self.bouton_generer_habilete.setObjectName("bouton_generer_habilete")
        self.verticalLayout.addWidget(self.bouton_generer_habilete)
        self.label_habilete = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_habilete.setFont(font)
        self.label_habilete.setAlignment(QtCore.Qt.AlignCenter)
        self.label_habilete.setObjectName("label_habilete")
        self.verticalLayout.addWidget(self.label_habilete)
        self.bouton_generer_or = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_generer_or.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_generer_or.setFont(font)
        self.bouton_generer_or.setObjectName("bouton_generer_or")
        self.verticalLayout.addWidget(self.bouton_generer_or)
        self.label_or = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_or.setFont(font)
        self.label_or.setAlignment(QtCore.Qt.AlignCenter)
        self.label_or.setObjectName("label_or")
        self.verticalLayout.addWidget(self.label_or)
        self.bouton_continuer = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_continuer.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_continuer.setFont(font)
        self.bouton_continuer.setObjectName("bouton_continuer")
        self.verticalLayout.addWidget(self.bouton_continuer)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.message_creation_personnage_1.setText(_translate("MainWindow", "Création du personnage"))
        self.bouton_generer_endurance.setText(_translate("MainWindow", "Générer Endurance"))
        self.label_endurance.setText(_translate("MainWindow", "Endurance:"))
        self.bouton_generer_habilete.setText(_translate("MainWindow", "Générer Habileté"))
        self.label_habilete.setText(_translate("MainWindow", "Habileté:"))
        self.bouton_generer_or.setText(_translate("MainWindow", "Générer Pièces D\'Or"))
        self.label_or.setText(_translate("MainWindow", "Nombre Pièces D\'Or:"))
        self.bouton_continuer.setText(_translate("MainWindow", "Continuer"))
