# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_bienvenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageBienvenu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_bienvenu = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.message_bienvenu.setFont(font)
        self.message_bienvenu.setAlignment(QtCore.Qt.AlignCenter)
        self.message_bienvenu.setObjectName("message_bienvenu")
        self.verticalLayout.addWidget(self.message_bienvenu)
        self.bouton_nouvelle_partie = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_nouvelle_partie.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_nouvelle_partie.setFont(font)
        self.bouton_nouvelle_partie.setObjectName("bouton_nouvelle_partie")
        self.verticalLayout.addWidget(self.bouton_nouvelle_partie)
        self.bouton_continuer_sauvegarde = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_continuer_sauvegarde.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_continuer_sauvegarde.setFont(font)
        self.bouton_continuer_sauvegarde.setObjectName("bouton_continuer_sauvegarde")
        self.verticalLayout.addWidget(self.bouton_continuer_sauvegarde)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.message_bienvenu.setText(_translate("MainWindow", "Livres dont vous êtes le héro"))
        self.bouton_nouvelle_partie.setText(_translate("MainWindow", "Nouvelle Partie"))
        self.bouton_continuer_sauvegarde.setText(_translate("MainWindow", "Continuer Progression"))
