# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_creation_personnage_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageCreationPersonnage3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 814)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_depart = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.message_depart.setFont(font)
        self.message_depart.setAlignment(QtCore.Qt.AlignCenter)
        self.message_depart.setWordWrap(True)
        self.message_depart.setObjectName("message_depart")
        self.verticalLayout.addWidget(self.message_depart)
        self.message_objets = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.message_objets.setFont(font)
        self.message_objets.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.message_objets.setWordWrap(True)
        self.message_objets.setObjectName("message_objets")
        self.verticalLayout.addWidget(self.message_objets)
        self.bouton_generer_objet = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_generer_objet.setFont(font)
        self.bouton_generer_objet.setObjectName("bouton_generer_objet")
        self.verticalLayout.addWidget(self.bouton_generer_objet)
        self.label_objet = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_objet.setFont(font)
        self.label_objet.setAlignment(QtCore.Qt.AlignCenter)
        self.label_objet.setObjectName("label_objet")
        self.verticalLayout.addWidget(self.label_objet)
        self.bouton_continuer = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_continuer.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_continuer.setFont(font)
        self.bouton_continuer.setObjectName("bouton_continuer")
        self.verticalLayout.addWidget(self.bouton_continuer)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.message_depart.setText(_translate("MainWindow", "<html><head/><body><p>Au départ de votre aventure, vous êtes vêtu d\'une tunique et d\'une cape de Seigneur Kaï, toutes deux de couleur verte. Le matériel dont vous disposez pour assurer votre survie est par ailleurs réduit au minimum. Vous possédez une Hache et un Sac à Dos qui contient un Repas. </p></body></html>"))
        self.message_objets.setText(_translate("MainWindow", "<html><head/><body><p>Dans les ruines fumantes du monastère détruit, vous avez découvert une Carte Géographique (Objet Speciaux) qui vous permet de vous orienter. Cette carte est soigneusement rangée dans une poche intérieure de votre tunique. Vous avez également découvert l\'un des objets suivants :</p><p>1 UNE ÉPÉE (Armes).</p><p>2 UN CASQUE (Objets Spéciaux), il ajoute 2 points d\'ENDURANCE à votre total.</p><p>3 DEUX REPAS (Repas).</p><p>4 UNE COTTE DE MAILLES (Objets Spéciaux), elle ajoute 4 points d\'ENDURANCE à votre total.</p><p>5 UNE MASSE D\'ARMES (Armes).</p><p>6 UNE POTION DE GUÉRISON (Sac à Dos), elle vous rend 4 points d\'ENDURANCE lorsque vous la buvez à l\'issue d\'un combat, mais vous ne disposez que d\'une seule dose.</p><p>7 UN BATON (Armes).</p><p>8 UNE LANCE (Armes).</p><p>9 DOUZE COURONNES (Pièces d\'Or).</p><p>0 UN GLAIVE (Armes).</p></body></html>"))
        self.bouton_generer_objet.setText(_translate("MainWindow", "Générer Objet"))
        self.label_objet.setText(_translate("MainWindow", "Objet:"))
        self.bouton_continuer.setText(_translate("MainWindow", "Continuer"))
