# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_creation_personnage_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageCreationPersonnage2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_creation_personnage_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.message_creation_personnage_2.setFont(font)
        self.message_creation_personnage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.message_creation_personnage_2.setObjectName("message_creation_personnage_2")
        self.verticalLayout.addWidget(self.message_creation_personnage_2)
        self.label_disciplines_kai = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_disciplines_kai.setFont(font)
        self.label_disciplines_kai.setAlignment(QtCore.Qt.AlignCenter)
        self.label_disciplines_kai.setObjectName("label_disciplines_kai")
        self.verticalLayout.addWidget(self.label_disciplines_kai)
        self.combobox_kai_1 = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_kai_1.setMinimumSize(QtCore.QSize(0, 75))
        self.combobox_kai_1.setObjectName("combobox_kai_1")
        self.verticalLayout.addWidget(self.combobox_kai_1)
        self.combobox_kai_2 = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_kai_2.setMinimumSize(QtCore.QSize(0, 75))
        self.combobox_kai_2.setObjectName("combobox_kai_2")
        self.verticalLayout.addWidget(self.combobox_kai_2)
        self.combobox_kai_3 = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_kai_3.setMinimumSize(QtCore.QSize(0, 75))
        self.combobox_kai_3.setObjectName("combobox_kai_3")
        self.verticalLayout.addWidget(self.combobox_kai_3)
        self.combobox_kai_4 = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_kai_4.setMinimumSize(QtCore.QSize(0, 75))
        self.combobox_kai_4.setObjectName("combobox_kai_4")
        self.verticalLayout.addWidget(self.combobox_kai_4)
        self.combobox_kai_5 = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_kai_5.setMinimumSize(QtCore.QSize(0, 75))
        self.combobox_kai_5.setObjectName("combobox_kai_5")
        self.verticalLayout.addWidget(self.combobox_kai_5)
        self.bouton_continuer = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_continuer.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_continuer.setFont(font)
        self.bouton_continuer.setObjectName("bouton_continuer")
        self.verticalLayout.addWidget(self.bouton_continuer)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.message_creation_personnage_2.setText(_translate("MainWindow", "Création du personnage"))
        self.label_disciplines_kai.setText(_translate("MainWindow", "Disciplines Kai"))
        self.bouton_continuer.setText(_translate("MainWindow", "Continuer"))
