# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_supprimer_objet.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageSupprimerObjet(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bouton_annuler = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_annuler.setFont(font)
        self.bouton_annuler.setObjectName("bouton_annuler")
        self.gridLayout_2.addWidget(self.bouton_annuler, 3, 1, 1, 1)
        self.combobox_objet = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.combobox_objet.setFont(font)
        self.combobox_objet.setObjectName("combobox_objet")
        self.gridLayout_2.addWidget(self.combobox_objet, 1, 0, 1, 2)
        self.bouton_supprimer = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_supprimer.setFont(font)
        self.bouton_supprimer.setObjectName("bouton_supprimer")
        self.gridLayout_2.addWidget(self.bouton_supprimer, 3, 0, 1, 1)
        self.label_supprimer_objet = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_supprimer_objet.setFont(font)
        self.label_supprimer_objet.setAlignment(QtCore.Qt.AlignCenter)
        self.label_supprimer_objet.setObjectName("label_supprimer_objet")
        self.gridLayout_2.addWidget(self.label_supprimer_objet, 0, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bouton_annuler.setText(_translate("MainWindow", "Annuler"))
        self.bouton_supprimer.setText(_translate("MainWindow", "Supprimer"))
        self.label_supprimer_objet.setText(_translate("MainWindow", "Supprimer Un Objet"))
