# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_chapitre.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageChapitre(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.titre_chapitre = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.titre_chapitre.setFont(font)
        self.titre_chapitre.setAlignment(QtCore.Qt.AlignCenter)
        self.titre_chapitre.setObjectName("titre_chapitre")
        self.verticalLayout.addWidget(self.titre_chapitre)
        self.texte_chapitre = QtWidgets.QLabel(self.centralwidget)
        self.texte_chapitre.setMinimumSize(QtCore.QSize(0, 250))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.texte_chapitre.setFont(font)
        self.texte_chapitre.setAlignment(QtCore.Qt.AlignCenter)
        self.texte_chapitre.setWordWrap(True)
        self.texte_chapitre.setObjectName("texte_chapitre")
        self.verticalLayout.addWidget(self.texte_chapitre)
        self.bouton_choix_1 = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_choix_1.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bouton_choix_1.setFont(font)
        self.bouton_choix_1.setObjectName("bouton_choix_1")
        self.verticalLayout.addWidget(self.bouton_choix_1)
        self.bouton_choix_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_choix_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bouton_choix_2.setFont(font)
        self.bouton_choix_2.setObjectName("bouton_choix_2")
        self.verticalLayout.addWidget(self.bouton_choix_2)
        self.bouton_choix_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_choix_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bouton_choix_3.setFont(font)
        self.bouton_choix_3.setObjectName("bouton_choix_3")
        self.verticalLayout.addWidget(self.bouton_choix_3)
        self.bouton_choix_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_choix_4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bouton_choix_4.setFont(font)
        self.bouton_choix_4.setObjectName("bouton_choix_4")
        self.verticalLayout.addWidget(self.bouton_choix_4)
        self.bouton_feuille_aventure = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_feuille_aventure.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bouton_feuille_aventure.setFont(font)
        self.bouton_feuille_aventure.setObjectName("bouton_feuille_aventure")
        self.verticalLayout.addWidget(self.bouton_feuille_aventure)
        self.bouton_quitter = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_quitter.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bouton_quitter.setFont(font)
        self.bouton_quitter.setObjectName("bouton_quitter")
        self.verticalLayout.addWidget(self.bouton_quitter)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titre_chapitre.setText(_translate("MainWindow", "Titre"))
        self.texte_chapitre.setText(_translate("MainWindow", "Texte"))
        self.bouton_choix_1.setText(_translate("MainWindow", "Choix 1"))
        self.bouton_choix_2.setText(_translate("MainWindow", "Choix 2"))
        self.bouton_choix_3.setText(_translate("MainWindow", "Choix 3"))
        self.bouton_choix_4.setText(_translate("MainWindow", "Choix 4"))
        self.bouton_feuille_aventure.setText(_translate("MainWindow", "Voir la feuille d\'aventure"))
        self.bouton_quitter.setText(_translate("MainWindow", "Quitter"))
