# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_selection_livre.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageSelectionLivre(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_selection_livre = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.message_selection_livre.setFont(font)
        self.message_selection_livre.setAlignment(QtCore.Qt.AlignCenter)
        self.message_selection_livre.setWordWrap(True)
        self.message_selection_livre.setObjectName("message_selection_livre")
        self.verticalLayout.addWidget(self.message_selection_livre)
        self.combobox_selection_livre = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_selection_livre.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.combobox_selection_livre.setFont(font)
        self.combobox_selection_livre.setObjectName("combobox_selection_livre")
        self.verticalLayout.addWidget(self.combobox_selection_livre)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.bouton_selectionner_livre = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_selectionner_livre.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_selectionner_livre.setFont(font)
        self.bouton_selectionner_livre.setObjectName("bouton_selectionner_livre")
        self.verticalLayout_2.addWidget(self.bouton_selectionner_livre)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.message_selection_livre.setText(_translate("MainWindow", "<html><head/><body><p>Selectionnez le livre dont vous </p><p>voulez être le héro</p></body></html>"))
        self.bouton_selectionner_livre.setText(_translate("MainWindow", "Selectionner"))
