# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_quitter.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageQuitter(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_quitter = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.message_quitter.setFont(font)
        self.message_quitter.setAlignment(QtCore.Qt.AlignCenter)
        self.message_quitter.setObjectName("message_quitter")
        self.verticalLayout.addWidget(self.message_quitter)
        self.bouton_continuer = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_continuer.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_continuer.setFont(font)
        self.bouton_continuer.setObjectName("bouton_continuer")
        self.verticalLayout.addWidget(self.bouton_continuer)
        self.bouton_sauvegarder_quitter = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_sauvegarder_quitter.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_sauvegarder_quitter.setFont(font)
        self.bouton_sauvegarder_quitter.setObjectName("bouton_sauvegarder_quitter")
        self.verticalLayout.addWidget(self.bouton_sauvegarder_quitter)
        self.bouton_quitter_sans_sauvegarder = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_quitter_sans_sauvegarder.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bouton_quitter_sans_sauvegarder.setFont(font)
        self.bouton_quitter_sans_sauvegarder.setObjectName("bouton_quitter_sans_sauvegarder")
        self.verticalLayout.addWidget(self.bouton_quitter_sans_sauvegarder)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.message_quitter.setText(_translate("MainWindow", "Que voulez-vous faire?"))
        self.bouton_continuer.setText(_translate("MainWindow", "Continuer"))
        self.bouton_sauvegarder_quitter.setText(_translate("MainWindow", "Sauvegarder et quitter"))
        self.bouton_quitter_sans_sauvegarder.setText(_translate("MainWindow", "Quitter sans sauvegarder"))
